[package]
name = "tuple_len"
authors.workspace = true
version = "0.1.1"
edition.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
discription.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
name = "tuple_len"

[dependencies]
tuple_macro = { version = "0.1.1", workspace = true, path = "tuple_macro" }

[features]
16 = ["tuple_macro/16"]
32 = ["tuple_macro/32"]
64 = ["tuple_macro/64"]


